language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements/test.txt
- pip install nose
script: nosetests tests/
deploy:
  provider: pypi
  user: davydany
  password:
    secure: Ur+LDJYUCr55gm1x/fye9NHB2R/QcBGEXIAk3F++EWxV9npjuFirGwzktmc9CSg4tKS/2CxLl3GdXyEtj2wZmjiG13NgAIsYO5NewbhCiMCemTH6IgSLkPSxDZYNu06Sd4JS1jyysZQ/ZW87RoVGGav1aLUNzd8d2uuwhHMGILXX8KJ2AIv0gNlPMLqZlqxWhz2X7opq3t5cTVx03YrsiYrHOjNPeTkkbTTW4mWjyajyaGu5m9eeiTPcu5bvhL2F5AAbC1LR/5n+u/aJFKqPFgu79T4v/cdkcDU9alTjhI5VRIlW3t5i2q7bcU0zYj1umwuPgNEL6u4WBBvqY0b9bW8JoHE52zmiRi5TmfU4P3ndsB62tdqG5k33+HzxykInDSfsBQXzuUfBk8OMju5o5/OCRHO4gdNMeupxB0cyU1WuxEoXm9X9TDLovMbjaIao8RYdtD5ztFVDTTFgOHTA9ECH9hRtgfy9mwC14ASw8ntrIsfv2BvqWQO4Ho1MXlJXi3p2OAVPOd8QNKXr6svjBxt+6eBf6FgOvLUCrXpXL2wKOJJtxkYs8wpis9jCHdpcPqjJwg20CedWoMkL8Z9+4EfbDOdq/IKjRphwbuoy+D9N75FTR6M4PiciXs69UZVWTWKBnEU1M3KkheFqmm/T8SSMLkts4kGXAukpI1OY9yM=
  on:
    distributions: sdist bdist_wheel
    repo: aeroxis/farmer
    tags: true
